fixtures:
  repositories:
    host:
      repo: 'git://github.com/puppetlabs/puppetlabs-host_core.git'
      ref: '1.0.1'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.25.1'
  symlinks:
    hosts: "#{source_dir}"
