---
language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.1"
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.3"
    - PUPPET_GEM_VERSION="~> 3.4"
    - PUPPET_GEM_VERSION="~> 3.5"
    - PUPPET_GEM_VERSION="~> 3.6"
    - PUPPET_GEM_VERSION="~> 3.7"
    - PUPPET_GEM_VERSION="~> 3.8"
    - PUPPET_GEM_VERSION="~> 3" PARSER="future"
    - PUPPET_GEM_VERSION="~> 4.0"
    - PUPPET_GEM_VERSION="~> 4.1"
    - PUPPET_GEM_VERSION="~> 4"

sudo: false

script: 'bundle exec metadata-json-lint metadata.json && bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.1"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.1"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4"

notifications:
  email: false
